# Generated by Django 4.2.4 on 2023-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='heading',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
