# Generated by Django 4.2.4 on 2023-08-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='heading',
            field=models.TextField(),
        ),
    ]
