# Generated by Django 4.2.4 on 2023-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user_download_count',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user_email_sent',
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('link', 'link')], default='null', max_length=20),
        ),
    ]
