# Generated by Django 4.2.4 on 2023-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='compiler',
            field=models.TextField(blank=True, null=True),
        ),
    ]
