# Generated by Django 4.2.4 on 2023-08-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=23, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
