# Generated by Django 4.2.4 on 2023-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
