# Generated by Django 4.2.4 on 2023-09-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_course_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_completed',
        ),
    ]
